name: build-varnish-7-5-0-alpine

on:
  push:
    paths:
      - Dockerfile.base
      - .github/workflows/build-varnish-7-5-0-alpine.yml
    branches:
      - feature/webgrip
  workflow_dispatch:

jobs:
  varnish-7-5-0-alpine:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: images/varnish/7.5.0-alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            webgrip/magento-varnish:7.5.0-alpine
