name: build-nginx-1-18

on: workflow_dispatch

jobs:
  nginx-1-18:
    runs-on: webgrip-actions-runner
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: images/nginx/1.18
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            webgrip/magento-nginx:1.18
