name: build-rabbitmq-3-11

on: workflow_dispatch

jobs:
  rabbitmq-3-11:
    runs-on: [self-hosted, Linux, X64]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: images/rabbitmq/3.11
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            webgrip/magento-rabbitmq:3.11
